//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaPortalNpm
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailNpm
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string Message { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    }
}
