<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="partners.aspx.cs" Inherits="BaPortalNpm.partners" %>

<asp:Content ID="BodyContentnpm" style="max-width: 100%;" ContentPlaceHolderID="MainContent" runat="server">
<div id="partnersMap" class="partner-padd">
    <div class="wrapper width-grid" style="margin-top:120px;">
        <div class="nomap-desktop">

            <!-- Image Map Generated by http://www.image-map.net/ -->
            <img src="https://npm-int.com/wp-content/themes/npm/img/MapGifFix.gif" usemap="#image-map">

            <map name="image-map">
                <area target="_top" onclick="myFunctionnAMERICA()" alt="N.AMERICA" title="N.AMERICA" href="javascript:void(0);" coords="8,39,311,245" shape="rect">
                <area target="_top" onclick="myFunctionsAMERICA()" alt="S.AMERICA" title="S.AMERICA" href="javascript:void(0);" coords="14,248,313,456" shape="rect">
                <area target="_top" onclick="myFunctionAFRICA()" alt="AFRICA" title="AFRICA" href="javascript:void(0);" coords="633,420,329,176" shape="rect">
                <area target="_top" onclick="myFunctionEUROPE()" alt="EUROPE" title="EUROPE" href="javascript:void(0);" coords="313,39,643,174" shape="rect">
                <area target="_top" onclick="myFunctionASIA()" alt="ASIA" title="ASIA" href="javascript:void(0);" coords="645,12,933,311" shape="rect">
                <area target="_top" onclick="myFunctionAUSTR()" alt="AUSTRALIA" title="AUSTRALIA" href="javascript:void(0);" coords="934,257,1177,455" shape="rect">
            </map>
        </div>
        <div class="nomap-mobile">
            <img src="https://npm-int.com/wp-content/themes/npm/img/MapMobileGifFix.gif" alt="Logo">
        </div>
        <!--s amerika-->
        <div class="row">
            <div class="col-5">
                <div class="center cursor-pointer ">
                    <a class="btn  usa" data-toggle="modal" data-target="#exampleModal">
                        <!--img  src="https://npm-int.com/wp-content/uploads/2018/10/Map-Place2.gif"-->
                        <!--	 <p  class="text-grid-tab text-days"></p>-->
                    </a>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel-close" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content padding1">
                            <div class="modal-body">
                                <!--USA-->
                                <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
                                    <div class="col-md-4 col-12 align-self-center">
                                        <img class="map-height" src="https://npm-int.com/wp-content/uploads/2018/11/Tamara-Sachs-Signature.png">
                                    </div>
                                    <div class="col-md-8 col-12">
                                        <div class="center cursor-pointer scroll-modal">
                                            <p class="text-left"></p><h3>NPM USA</h3>
                                            <p>5348 Vegas Drive Las Vegas, NV 89108, USA</p>
                                            <p><a href="https://www.npm-usa.com">www.npm-usa.com</a></p>
                                            <p>Tel: 727-773-7710, Email: facenakedstudio@gmail.com</p>
                                            <p>Instagram: npm_technologies</p>
                                            <p>Tamarasachspmu</p>
                                            <p><a href="https://www.facebook.com/npmbeauty">FaceBook 1</a></p>
                                            <p><a href="https://www.facebook.com/npmtech">FaceBook 2</a></p>
                                            <p><a href="https://www.youtube.com/npmusacanada">YouTube</a></p>
                                            <p></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->
            </div>
            <!--test  pomenat map-->



            <!--Europe-->
            <div class="col-5 no-padding ">
                <!--China-->
                <div class="center cursor-pointer ">
                    <a class="btn  china2" data-toggle="modal" data-target="#exampleModal12">
                        <!--img  src="https://npm-int.com/wp-content/uploads/2018/10/Map-Place2.gif"-->
                        <!--			 <p class="text-grid-tab">CHINA</p>-->
                    </a>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal12-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel12-close" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content padding2">
                            <div class="modal-body">
                                <!--row3 -->
                                <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
                                    <div class="col-md-4 col-12 align-self-center">
                                        <img class="map-height" src="https://npm-int.com/wp-content/uploads/2018/10/Stella-Liang.jpg">
                                    </div>
                                    <div class="col-md-8 col-12">
                                        <div class="center cursor-pointer scroll-modal">
                                            <p class="text-left"></p><h3>Changsha Weiting Beauty LTD</h3>
                                            <p>Wanda Plaze Changsha, Hunan, China</p>
                                            <p><a href="https://www.npm-china.cn/">https://www.npm-china.cn/</a></p>
                                            <p>Tel: 400-8228-010, Email: stella@npm-china.cn</p>
                                            <p>WeChat: Npmchina</p>
                                            <p><a href="https://www.facebook.com/profile.php?id=100013078629577">FaceBook</a></p>
                                            <p></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->

                <!--INDIA-->
                <div class="center cursor-pointer ">
                    <a class="btn india no-maptitle" data-toggle="modal" data-target="#exampleModal13">
                        <!--img  src="https://npm-int.com/wp-content/uploads/2018/10/Map-Place2.gif"-->
                        <!-- <p class="text-grid-tab">INDIA</p>-->
                    </a>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal13-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel13-close" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content padding3">
                            <div class="modal-body">
                                <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
                                    <div class="col-md-4 col-12 align-self-center">
                                        <img class="map-height" src="https://npm-int.com/wp-content/uploads/2018/11/photo.jpg">
                                    </div>
                                    <div class="col-md-8 col-12">
                                        <div class="center cursor-pointer scroll-modal">
                                            <p class="text-left"></p><h3>Dermatec</h3>
                                            <p>Cra 43 A # 7-50A<br>
                                                Office 1012, Tower DANN<br>
                                                City: MEDELLÍN<br>
                                                Country: COLOMBIA</p>
                                            <p><a href="https://www.dermatec.com.co/categoria-producto/micropigmentacion/equipo-npm-micropigmentacion/">https://www.dermatec.com.co/categoria-producto/micropigmentacion/equipo-npm-micropigmentacion/</a></p>
                                            <p>Tel:</p>
                                            <p>+57 3155059533 (Móvil)<br>
                                                +57 3155615369 (Móvil)<br>
                                                +57 4 2685116 (Fixed)</p>
                                            <p>Email:</p>
                                            <ul>
                                                <li>gerencia@dermatec.com.co</li>
                                                <li>dermatecsas@gmail.com</li>
                                                <li>npm.pmu.colombia@gmail.com</li>
                                            </ul>
                                            <p>Social media links (business facebook, business Instagram, business linkedin…)</p>
                                            <ul>
                                                <li>@npmcolombia</li>
                                                <li>@dermatecsas</li>
                                                <li>@dermatecmicropigmentacion</li>
                                                <li>@dermopigmentacion</li>
                                                <li>#npmcolombia</li>
                                                <li>#dermatecsas</li>
                                                <li>#dermatecmicropigmentacion</li>
                                                <li>#dermopigmentacion</li>
                                            </ul>
                                            <p></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->

                <!-- / popup INDIA-->
            </div>
        </div>
        <div class="row">
            <!--n amerika-->
            <div class="col-5  text-left" style="">
                <p class="text-grid-tab"></p>
            </div>
            <!--afrika-->
            <div class="col-6 margin-map ">
                <!--icon click  to Germany popup-->
                <div class="center cursor-pointer ">
                    <a class="btn germany " data-toggle="modal" data-target="#exampleModal14">
                        <!--img  src="https://npm-int.com/wp-content/uploads/2018/10/Map-Place2.gif"-->
                        <!-- <p class="text-grid-tab">Germany</p>-->
                    </a>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal14-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel14-close" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content padding4">
                            <div class="modal-body">
                                <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
                                    <div class="col-md-4 col-12 align-self-center">
                                        <img class="map-height" src="https://npm-int.com/wp-content/uploads/2018/10/logo_abaco_i_glowa.jpg">
                                    </div>
                                    <div class="col-md-8 col-12">
                                        <div class="center cursor-pointer scroll-modal">
                                            <p class="text-left"></p><h3>Abacosun</h3>
                                            <p>Olgierda 45, Gdynia 81-534 , Poland</p>
                                            <p><a href="https://www.abacosun.pl">&nbsp;www.abacosun.pl</a></p>
                                            <p>Tel: +&nbsp; 48 58 664 64 51 , Email: abaco@abacosun.pl</p>
                                            <p></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->

                <!-- / popup Germany-->

                <!--icon click THE NETHERLANDS popup-->
                <div class="center cursor-pointer ">
                    <a class="btn niderlandy " data-toggle="modal" data-target="#exampleModal15">
                        <!--img  src="https://npm-int.com/wp-content/uploads/2018/10/Map-Place2.gif"-->
                        <!-- <p class="text-grid-tab">THE NETHERLANDS</p>-->
                    </a>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal15-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel15-close" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content padding5">
                            <div class="modal-body">
                                <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
                                    <div class="col-md-4 col-12 align-self-center">
                                        <img class="map-height" src="https://npm-int.com/wp-content/uploads/2018/10/IMG_4254.png">
                                    </div>
                                    <div class="col-md-8 col-12">
                                        <div class="center cursor-pointer scroll-modal">
                                            <p style="text-align:left" class=""></p><h3>Tinails &amp; Beauty</h3>
                                            <p>Tina Pmu Specialiste,&nbsp;Veerweg 18,&nbsp;5863AR Blitterswijck</p>
                                            <p><a href="https://www.permanentmakeuptina.nl">www.permanentmakeuptina.nl</a></p>
                                            <p>Tel: 0653602959 , Email: info@tinails.nl</p>
                                            <p><a href="https://www.facebook.com/tinailsenbeauty/?fref=ts">FaceBook</a></p>
                                            <p></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->

                <!-- / popup THE NETHERLANDS-->

                <!--click icon popup THE Israel-->
                <div class="center cursor-pointer ">
                    <a class="btn israel " data-toggle="modal" data-target="#exampleModal16">
                        <!--img  src="https://npm-int.com/wp-content/uploads/2018/10/Map-Place2.gif"-->
                        <!--	<p class="text-grid-tab">ISRAEL</p>-->
                    </a>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal16-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel16-close" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content padding6">
                            <div class="modal-body">
                                <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
                                    <div class="col-md-4 col-12 align-self-center">
                                        <img class="map-height" src="https://npm-int.com/wp-content/uploads/2018/10/IMK7033.jpg">
                                    </div>
                                    <div class="col-md-8 col-12">
                                        <div class="center cursor-pointer scroll-modal">
                                            <p style="text-align:left" class=""></p><h3>Becas Medikal AŞ</h3>
                                            <p>Halkalı Merkez Mahallesi Dereboyu Caddesi<br>
                                                No:56 Balcon Plaza Kat:7 Küçükçekmece<br>
                                                İSTANBUL – TURKEY</p>
                                            <p><a href="https://www.becasmedikal.com">www.becasmedikal.com</a></p>
                                            <p>Tel: 00902128859999,&nbsp;Email: burcusoydan@becasmedikal.com,&nbsp;Whatsapp: 00905326060099</p>
                                            <p><a href="https://www.facebook.com/becas.medikal/?ref=br_rs">FaceBook</a></p>
                                            <p><a href="https://www.instagram.com/becasmedikal/?hl=tr">Instagram</a></p>
                                            <p></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->
                <!-- / *********************popup THE Israel*******************-->
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
    
</asp:Content>








