//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaPortalNpm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeminarsNpm
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string When { get; set; }
        public string Where { get; set; }
        public string PhoneNumber { get; set; }
        public string LinkToPaypal { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> InternalDate { get; set; }
    }
}
